name: dating_demo
description: Dating Demo

#####  Instruction

# Add key key.properties first before build
# Build apk: flutter build apk --no-sound-null-safety

# Build generate: flutter pub run build_runner build --delete-conflicting-outputs
# flutter packages pub run build_runner build --delete-conflicting-outputs
# Watch: flutter pub run build_runner watch --delete-conflicting-outputs

# Generate Json file: https://plugins.jetbrains.com/plugin/12755-json2json-serializable
#                     https://javiercbk.github.io/json_to_dart/
# Generate Image assets: https://github.com/FlutterGen/flutter_gen

# create module: flutter create --template=package module_name
# generate get_cli:open and read file getx_structure_readme.md

### Thing to do for IOSTechniqueModule
# https://pub.dev/packages/qr_code_scanner
# https://firebase.flutter.dev/docs/installation/ios
# https://facebook.meedu.app/#/ios
# https://pub.dev/packages/google_maps_flutter
#// TODO: for release
#// Add SHA-1 on release key
#// Add Hash key on release https://developers.facebook.com/docs/facebook-login/android/?locale=en
#// For iOS Build
#// https://firebase.flutter.dev/docs/installation/ios
#// FB sdk: https://facebook.meedu.app/#/ios


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+50

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  get_cli: ^1.7.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  flutter_reaction_button: ^1.0.8
  share_plus: ^3.0.4

  ## Rest API
  retrofit: ^2.0.1
  logger: ^1.0.0  #for logging purpose
  dio: ^4.0.1
  pretty_dio_logger: ^1.2.0-beta-1
  synchronized: ^3.0.0
  retry: ^3.1.0
  rxdart: ^0.27.1
  http: ^0.13.4

  ## Json format
  json_serializable: ^6.1.4
  #  json_annotation: ^4.0.1

  #####  View
  velocity_x: ^3.3.0
  like_button: ^2.0.2
  overlay_support: ^1.2.0
  keyboard_dismisser: ^2.0.0
  photo_view: ^0.12.0
  dotted_line: ^3.0.0
  animated_text_kit: ^4.1.1
  swipe_cards: ^1.0.0
  flutter_local_notifications: ^8.2.0

  ## Loading process
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  pull_to_refresh: 2.0.0

  ## Animation
  animate_do: ^2.0.0
  scroll_to_index: ^2.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0

  ## WebView
  webview_flutter: ^2.0.9
  #  flutter_webview_plugin: ^0.4.0
  #  flutter_inappwebview: ^5.3.2

  ## Navigation
  auto_route: ^3.2.4

  ##### Config
  #  device_info: ^2.0.2
  device_info_plus: ^3.1.0
  flutter_keyboard_visibility: ^5.1.0
  connectivity_plus: ^2.2.0

  #####  Data
  intl: ^0.17.0
  flutter_html: ^2.1.0
  hive: ^2.0.2
  hive_flutter: ^1.1.0
  cached_network_image: ^3.1.0
  timeago: ^3.0.2
  url_launcher: ^6.0.10

  #####  Resource
  font_awesome_flutter: ^9.1.0
  flutter_svg: ^0.22.0
  image_picker: 0.8.4+4

  #####  Firebase
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.10

  #package_info for IOS: Clean the Xcode build folder with: XCode Menu -> Product -> (Holding Option Key) Clean build folder.
  #  package_info: ^2.0.2
  package_info_plus: ^1.3.0

  #package internal import
  logger_and_error:
    path: ./packages/logger_and_error

#dependency_overrides:

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  breakpoint: ^1.2.0
  build_runner: ^2.0.6
  retrofit_generator: ^2.0.1
  flutter_gen_runner: ^4.1.5
  hive_generator: ^1.0.1
  flutter_lints: ^1.0.4
  auto_route_generator: ^3.2.3
  #  mockito: ^5.0.0
  # BEGIN GENERATE MODEL
  # Auto generate map model from json with command: flutter packages pub run build_runner build --delete-conflicting-outputs
  # build_runner:
  # json_serializable:
  # END GENERATE MODEL

# BEGIN CONFIG LAUNCHER ICON
# After config then run command: flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/ic_launcher.png"
# END CONFIG LAUNCHER ICON

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    null_safety: true
#  colors:
#    inputs:
#      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/icons/common/
    - assets/img/

  fonts:
    - family: SFUIText
      fonts:
        - asset: assets/fonts/SFUIText/SFUIText-Light.ttf
          weight: 300
        - asset: assets/fonts/SFUIText/SFUIText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFUIText/SFUIText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFUIText/SFUIText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFUIText/SFUIText-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFUIText/SFUIText-Heavy.ttf
          weight: 800