// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDaP6_YxN-viEslyvRhN6uRJ2bXQ0wNag',
    appId: '1:1086338871919:android:ae6e21474c5c3cec2d939a',
    messagingSenderId: '1086338871919',
    projectId: 'datingapp-75502',
    storageBucket: 'datingapp-75502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5R3c6CqJnOdnp3Rjgl6rfa9y4rPlLc4',
    appId: '1:1086338871919:ios:92c010d00748ab102d939a',
    messagingSenderId: '1086338871919',
    projectId: 'datingapp-75502',
    storageBucket: 'datingapp-75502.appspot.com',
    iosClientId: '1086338871919-qk119and9jkv9uot19eit55j0ffjc7ek.apps.googleusercontent.com',
    iosBundleId: 'com.dating.demo.kyo',
  );
}
