import 'package:dating_demo/all_file/all_file.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  _buildLangVn() {
    return {
      //app update
      'updateAvailable': 'Đã có bản cập nhật mới',
      'update': 'Cập nhật',
      'later': 'Để sau',

      // Menu
      'navHome': 'Trang chủ',
      'navStore': 'Cửa hàng',
      'navNotify': 'Thông báo',
      'userNav': 'Tài khoản',
      'yourOrderNav': 'Đơn hàng của bạn',
      'aboutNav': 'Giới thiệu',
      'contactNav': 'Liên hệ',
      'operationNav': 'Quy chế hoạt động',
      'termNav': 'Điều kiện giao dịch chung',
      'privacyNav': 'Chính sách bảo mật thông tin',
      'shippingInfoNav': 'Thông tin vận chuyển và giao nhận',
      'payInstructNav': 'Hướng dẫn thanh toán',
      'discountNav': 'Ưu đãi',
      'plantFeature': 'Bác sĩ tư vấn',
      'productTop': 'Bác sĩ khuyên dùng',

      //Discount
      'selectDiscount': 'Chọn mã giảm giá',
      'apply': 'Áp dụng',
      'inputVoucher': 'Nhập mã voucher',
      'check': 'Kiểm tra',
      'canChoose': 'Có thể chọn',
      'chooseOrInputCoupon': 'Chọn hoặc nhập mã khuyến mãi',
      'discountApplied': 'Khuyến mãi đang áp dụng',
      'emptyCoupon': 'Chưa chọn mã',
      'hadChosen': 'mã đã chọn',
      // Common
      'welcomeToApp': 'Chào mừng đến với Bác Sĩ Cây Xanh!',
      'or': 'hoặc',
      'phoneInput': 'Nhập số điện thoại của bạn',
      'continue': 'Tiếp tục',
      'search': 'Tìm kiếm',
      'checkout': 'Thanh toán',
      'viewdetail': 'Xem chi tiết',
      'buyagain': 'Mua lại',
      'all': 'Tất cả',
      'allProduct': 'Tất Cả \nSản Phẩm',
      'customer': 'Khách hàng',
      'verified': 'Đã xác thực',
      'anonymous': 'Ẩn danh',
      'logout': 'Đăng xuất',
      'notLogin': 'Chưa đăng nhập',
      'orderDetail': 'Thông tin đơn hàng',
      'shippingaddress': 'Địa chỉ nhận hàng',
      'productlist': 'Danh sách sản phẩm',
      'paymentmethod': 'Phương thức thanh toán',
      'fullName': 'Họ và tên',
      'phoneNumber': 'Số điện thoại',
      'save': 'Lưu',
      'review': 'Đánh giá',
      'instruction': 'Hướng dẫn',
      'sort': 'Sắp xếp',
      'showMore': 'Xem thêm',
      'showLess': 'Thu gọn',
      'week': 'Tuần',
      'date': 'Ngày',
      'completed': 'Đã hoàn thành',
      'onGoing': 'Đang thực hiện',
      'upNext': 'Sắp tới',
      'nextStep': 'Bước tiếp theo',
      'goBack': 'Trở về',
      'discoveryTag': 'Khám phá chủ đề',
      'newsTop': 'Bài viết nổi bật',
      'yes': 'Có',
      'no': 'Không',
      'selectPlant2': 'Chọn cây',
      'commentInput': 'Nhập bình luận',
      'news': 'Tin tức',
      'goBackHome': 'Trở về trang chủ',
      'thankYou': 'Cảm ơn bạn!',
      'processingYourOrder': 'Đơn hàng của bạn đang được xử lý',
      'cancel': 'Huỷ',

      //comment
      'loginToComment': 'Hãy đăng nhập để tham gia bình luận',
      'postComment': 'Đăng bình luận',
      'pleaseTryAgainInMinutes': 'Bạn mới đăng bình luận gần đây, xin vui lòng thử lại trong ít phút nữa',
      'postCommentSuccess': 'Đã đăng bình luận thành công',
      'mustLarger15Letters': 'Bạn phải nhập lớn hơn 15 ký tự',
      'larger15AndLeast150Letters':'Nhập lớn hơn 15 và nhỏ hơn 150 ký tự',
      'writeComment': 'Viết bình luận',
      'noComment': 'Hiện không có bình luận nào',
      'confirmDeleteComment':'Bạn có muốn xóa bình luận này không?',
      'deleteComplete':'Đã xóa thành công',
      'commentMore':'Xem thêm bình luận',


      // Error
      'errorMsg': 'Có lỗi xảy ra, vui lòng thử lại!',
      'inputErrorMsg': 'Vui lòng nhập thông tin!',
      'infoFoundErrorMsg': 'Không tìm thấy thông tin!',
      'phoneNotValid': 'Số điện thoại không đúng',
      'infoNotFound': 'Không tìm thấy thông tin, vui lòng quay lại sau!',

      // Sort
      'CreateOnDesc': 'Mới nhất',
      'PriceAsc': 'Giá tăng dần',
      'PriceDesc': 'Giá giảm dần',
      'NameAsc': 'Tên A->Z',
      'NameDesc': 'Tên Z->A',

      'DEFAULT': 'Mặc định',
      'CREATE_ON_ASC': 'Cũ nhất',
      'CREATE_ON_DESC': 'Mới nhất',
      'PRICE_ASC': 'Giá tăng dần',
      'PRICE_DESC': 'Giá giảm dần',
      'NAME_ASC': 'Tên A->Z',
      'NAME_DESC': 'Tên Z->A',

      // Plant
      'blog': 'Mẹo hay',
      'technique': 'Kỹ thuật',
      'bug': 'Trừ Sâu',
      'disease': 'Trừ bệnh',
      'nutrition': 'Dinh dưỡng',
      'beforeSow': 'trước khi gieo hạt',
      'selectYourPlant': 'Chọn loại cây trồng mà bạn quan tâm',
      'plantAlreadySelected': 'Cây đã có trong danh sách',
      'canBeFound': 'Có thể được tìm thấy ở cây',
      'symptomMsg': 'Biểu hiện',
      'treatNow': 'Biện pháp xử lý',
      'treatNowPest': 'Biện pháp điều trị',
      'precaution': 'Biện pháp phòng ngừa',
      'precautionPest': 'Biện pháp điều trị',
      'treatProduct': 'Sản phẩm đặc trị',
      'diseaseReason': 'Nguyên nhân gây bệnh',
      'recognize': 'Đặc điểm nhận biết',
      'consequence': 'Hậu quả',
      'sowDay': 'Ngày gieo hạt',
      'plantInfoUpdating': 'Thông tin cây trồng đang được cập nhật',
      'fieldSupervision': 'Giám sát đồng ruộng',
      'diseaseCanHave': 'Những bệnh có thể xuất hiện',
      'pestCanHave': 'Những loại sâu có thể xuất hiện',
      'tips': 'Mẹo',
      'task': 'Nhiệm vụ',
      'selectPlant': 'Chọn cây đang trồng',
      'useProduct': 'Sử dụng sản phẩm',
      'otherDisease': 'Bệnh khác của cây',
      'otherPest': 'Sâu khác có thể gặp ở cây',
      'otherPost': 'Bài viết liên quan',
      'plantBlog': 'Bài viết cây trồng',
      'productIsUpdating': 'Danh sách sản phẩm đang được cập nhật',
      'searchPlant': 'Tìm cây bạn muốn trồng',


      //author
      'authorInfo': 'Thông tin tác giả',

      //info
      'companyInfo': 'Công Ty TNHH Nông Nghiệp Công Nghệ Cao',
      'taxCode': 'Mã số thuế: ',
      'taxCodeBy': 'Do Sở Kế Hoạch và Đầu Tư Hà Tĩnh cấp lần đầu ngày 26/05/2017, cập nhật thay đổi vào ngày 04/12/2018',
      'productCertificate': 'Giấy chứng nhận đủ điều kiện sản xuất phân bón',
      'certificateNumber':'Số: 01 GCN/TTr - BVTV - PB, do Chi cục trồng trọt và bảo vệ thực vật Hà Tĩnh cấp ngày 3 tháng 10 năm 2019',
      'contactInfo': 'Thông tin liên hệ:',
      'contactAddress': 'Lô CN12, Cụm khu công nghiệp Phù Việt, Xã Phù Việt, Huyện Thạch Hà, Tỉnh Hà Tĩnh, VN',


      // Disease

      // Notify

      //Contact us
      'contactUs': 'Liên hệ với chúng tôi',
      'email': 'Email',
      'company': 'Công ty',
      'message': 'Tin nhắn',
      'content': 'Nội dung',
      'sendFeedback': 'Gửi phản hồi',
      'personalinfo': 'Thông tin cá nhân',
      'entervalidemail': 'Địa chỉ email nhập sai',
      'sentContact': 'Đã gửi thành công!',

      // Review Order
      'reviewOrder': 'Đánh giá đơn hàng',
      'writeReview': 'Viết đánh giá...',
      'sendReview': 'Gửi đánh giá',
      'reviewDone': 'Đã đánh giá',
      // Order
      'emptyOrderHistory': 'Không tìm thấy đơn hàng!',
      'cancelOrder': 'Hủy đơn hàng',
      'receiveOrder': 'Đã nhận hàng',
      'emptyOrders': 'Chưa có đơn hàng nào!',
      'orderStatusFollow': 'Theo dõi đơn hàng',
      'PENDING': 'Chờ xác nhận',
      'PROCESSING': 'Đang xử lý',
      'COMPLETE': 'Đang giao hàng',
      'RECEIVED_CONFIRMED': 'Đã nhận hàng',
      'CANCELLED': 'Đã hủy',

      // QR
      'qrScan': 'Quét mã QR',
      'qrScanMsg':
          'Vui lòng đưa mã QR của sản phẩm vào camera để quét sản phẩm',
      'qrInstructionMsg':
          'Mã QR có dạng tương tự như mã dưới và thường được in trên bao bì sản phẩm',
      'qrScanErrorMsg': 'Mã QR không đúng, xin vui lòng thử lại',

      // Address
      'shippingAddress': 'Địa chỉ giao hàng',
      'editAddress': 'Sửa địa chỉ',
      'addAddress': 'Thêm địa chỉ',
      'contactHint': 'Liên hệ',
      'address': 'Địa chỉ',
      'streetHint': 'Tòa nhà, tên đường,...',
      'stateHint': 'Tỉnh/Thành phố',
      'districtHint': 'Quận/Huyện',
      'townHint': 'Phường/Xã',
      'isSetDefaultAddress': 'Bạn có muốn chọn địa chỉ này làm mặc định?',


      // Payment
      'paymentMethod': 'Phương thức thanh toán',
      'shipCodeMsg': 'Thanh toán khi nhận hàng',
      'completePayment': 'Hoàn tất thanh toán',
      'lastPaymentInfo': 'Các thông tin khác',

      // Checkout
      'yourOrderItems': 'Đơn hàng của bạn',
      'subTotal': 'Tạm tính',
      'total': 'Tổng',
      'totalIncludeVAT': 'Tổng (Bao gồm VAT)',
      'includeVAT': '(Đã bao gồm VAT nếu có)',
      'totalPrice': 'Thành tiền',
      'shippingFee': 'Phí giao hàng',
      'discountTotal': 'Giảm',
      'discountPrice': 'Giảm giá',
      'agreementMsg':
          'Bằng cách tiếp tục thực hiện giao dịch mua này, bạn đồng ý với chúng tôi',
      'agreementPrivacy': 'Bằng việc đăng ký, bạn đồng ý với',
      'agreementPrivacyExpand': ' của chúng tôi',
      'proceedCheckout': 'Tiếp tục thanh toán',
      'confirmCancelOrder': 'Bạn có chắc muốn hủy đơn hàng?',
      'noteOrderCheckout': 'Ghi chú đơn hàng',
      'orderBuy': 'Đặt mua',

      // Sign In
      'login': 'Đăng nhập',
      'loginOrRegister': 'Đăng nhập hoặc đăng kí',
      'loginFacebook': 'Đăng nhập với Facebook',
      'loginGoogle': 'Đăng nhập với Google',
      'inputOtp': 'Nhập mã OTP',
      'inputOtpAuth': 'Nhập mã OTP để xác thực đơn hàng',
      'otpSentTo': 'Mã OTP đã được gửi qua số điện thoại: ',
      'otpTimeLast': 'Mã OTP có hiệu lực ',
      'sendAgain': 'Gửi lại',
      'sendAgainAfter': 'Vui lòng thử lại sau ',
      'checkPhoneNumber': 'Vui lòng kiểm tra lại số điện thoại!',
      'otpInvalid': 'Mã OTP không đúng!',
      'otpCode': 'Mã OTP',
      'getOtpCode': 'Lấy mã',
      'accountUseDifferent':
          'Tài khoảng đã được dùng cho phương thức đăng nhập khác',
      'otpSuccess': 'Xác thực OTP thành công',

      // Product
      'productNotFound': 'Không tìm thấy sản phẩm!',
      'productItem': 'Sản phẩm',
      'relatedProduct': 'Sản phẩm liên quan',
      'buy': 'Mua',
      'buyNow': 'Mua Ngay',
      'addToCard': 'Thêm vào giỏ hàng',
      'add': 'Thêm',
      'contentIsUpdating': 'Nội dung đang cập nhật',
      'imageIsUpdating': 'Hình ảnh đang cập nhật',
      'filterDone': 'Tìm sản phẩm',
      'filterPrice': 'Tìm theo giá',
      'orderBy': 'Sắp theo',
      'productCategory': 'Danh mục sản phẩm',
      'productsEmpty': 'Không có sản phẩm',
      'productTag': 'Nhãn',
      'productDescription': 'Mô tả sản phẩm',
      'userGuide': 'Hướng dẫn sử dụng',
      'ratingProduct': 'Đánh giá sản phẩm',
      'reviewIn': 'Nhận xét vào',
      'crossSell': 'Mua kèm',
      'moreFromCustomer': 'Xem ảnh bệnh liên quan',
      'close': 'Đóng',
      'quantity': 'Số lượng',
      'freeshipAmount': 'Freeship from order 200k',
      'buyLargeGoodCost': 'Mua sỉ giá tốt',
      'shipByDay': 'Nhận hàng sau 2 - 4 ngày',
      'addProduct': 'Thêm sản phẩm',
      'addProductSuccess': 'Thêm vào giỏ hàng thành công',
      'deleteCrossSellProduct': 'Đã xóa sản phẩm khỏi giỏ hàng',

      // Cart
      'emptyBag': 'Chưa chọn sản phẩm nào',
      'confirmDeleteItem': 'Bạn có chắc muốn xóa sản phẩm này?',
      'confirmDeleteAddress': 'Bạn có chắc muốn xóa địa chỉ này?',
      'confirmSignOut': 'Bạn có chắc muốn đăng xuất?',

      // Label
      '': '',
      'LOGIN': 'ĐĂNG NHẬP',
      'Cropper': 'Cắt ảnh',
      'You': 'Tôi',
      'Last reply on': 'Trả lời lần cuối vào',
      'Current Classes': 'Lớp đang học',
      'Next Lesson: ': 'Buổi học kế :',
      'Finished Classes': 'Lớp đã kết thúc',
      'Direct Contact': 'Liên hệ trực tiếp',
      'Feedback List': 'DS phản hồi',
      'Type here to search': 'Gõ vào đây để tìm kiếm',
      'Select Center': 'Chọn trung tâm',
      'Please enter at least 3 characters': 'Vui lòng nhập ít nhất 3 kí tự',
      'No results found': 'Không tìm thấy kết quả',
      'Comment': 'Bình luận',
      'Like': 'Thích',
      'share': 'Chia sẻ',
      'Next': 'Tiếp theo',
      'Get Started': 'Bắt đầu',
      'Done': 'Xong',
      'Home': 'Bảng tin',
      'Recent': 'Mới nhất',
      'Promotion': 'Khuyến mãi',
      'News': 'Tin tức',
      'Search by subject': 'Tìm theo tiêu đề',
      'LBL_SLIDE_1':
          'Kết nối phụ huynh/học sinh với nhà trường/giáo viên, dễ dàng tương tác và trao đổi mọi lúc, mọi nơi.',
      'LBL_SLIDE_2':
          'Mạng xã hội dành riêng cho giáo dục giúp phụ huynh tiện lợi theo dõi các hoạt động thường nhật của học sinh ở lớp học.',
      'LBL_SLIDE_3':
          'Cập nhật liên tục các nhận xét, đánh giá của giáo viên sau mỗi buổi học. Dễ dàng theo dõi tiến độ học tập, BTVN.',
      'LBL_SLIDE_4':
          'Và còn rất nhiều tính năng ấn tượng, hấp dẫn thường xuyên được DotB cập nhật liên tục. Mang lại trải nghiệm tuyệt vời nhất cho bạn.',
      'The language has been changed': 'Ngôn ngữ đã được thay đổi',
      'Your profile image was updated!': 'Cập nhật ảnh đại diện thành công!',
      'Schedules reminder': 'Nhắc lịch học',
      'LBL_REMINDER_AT_1': 'Ứng dụng sẽ gửi một thông báo nhắc nhở ',
      'LBL_REMINDER_AT_2': ' phút trước buổi học.',
      'Today': 'Hôm nay',
      'Attach Image': 'Ảnh đính kèm',
      'Incorrect username or password':
          'Tên đăng nhập hoặc mật khẩu không đúng',
      'Version': 'Phiên bản: ',
      'Forgot password?': 'Quên mật khẩu?',
      'Please wait for a while!': 'Vui lòng đợi trong giây lát!',
      'Enter your email address to request a password reset.':
          'Nhập số điện thoại hoặc email để khôi phục mật khẩu',
      'LBL_ENTER_CODE': 'Nhập mã xác nhận để khôi phục mật khẩu.',
      'LBL_ACCOUNT': 'Tài khoản',
      'LBL_FEEDBACK_LIST': 'Danh sách phản hồi',
      'LBL_MENU_HOME': 'Trang chủ',
      'LBL_MENU_CALENDAR': 'Lịch',
      'LBL_HOME_ATTENDANCE': 'Điểm danh',
      'LBL_DATE_ATTENDANCE': 'Ngày điểm danh',
      'LBL_MENU_PAYMENT': 'Thanh toán',
      'LBL_MENU_PROFILE': 'Cá nhân',
      'LBL_MENU_FEEDBACK': 'Phản hồi',
      'LBL_DOCUMENT': 'Tài liệu',
      'LBL_EMAIL_ADDRESS': 'Email',
      'LBL_PASSWORD': 'Mật khẩu',
      'LBL_CHANGE_PASSWORD': 'Đổi mật khẩu',
      'LBL_GENDER': 'Giới tính',
      'LBL_USERNAME_EMAIL': 'Tên đăng nhập/ Email',
      'LBL_BIRTHDATE': 'Ngày sinh',
      'LBL_ID': 'Mã học viên',
      'LBL_STATUS': 'Trạng thái',
      'LBL_LOGOUT': 'Đăng xuất',
      'LBL_PHONE': 'Số điện thoại',
      'LBL_CHANGE_LANGUAGE': 'Thay đổi ngôn ngữ',
      'LBL_SUB_CHANGE': 'Bạn muốn sử dụng ngôn ngữ nào?',
      'LBL_CHANGE_USER': 'Chuyển đổi tài khoản',
      'LBL_SUB_CHANGE_USER': 'Chọn tài khoản muốn chuyển đổi',
      'LBL_QR_CODE': 'Mã QR',
      'LBL_NICKNAME': 'Tên tiếng anh',
      'LBL_SCORE': 'Tổng điểm tích lũy',
      'LBL_SCORE_HISTORY': 'Lịch sử tích điểm',
      'LBL_AMOUNT': 'Tổng tiền: ',
      'LBL_SAVE': 'Lưu',
      'LBL_SAVE_LIST': 'Lưu danh sách',
      'LBL_SAVE_AND_SEND_NOTI': 'Lưu & Gửi TB',
      'LBL_CANCEL': 'Hủy bỏ',
      'LBL_SUBMIT': 'GỬI',
      'LBL_NOTIFICATIONS': 'Thông báo',
      'LBL_TOPIC': 'Bài học: ',
      'LBL_ACTIVITIES': 'Nội dung: ',
      'LBL_HOMEWORK': 'Bài tập về nhà: ',
      'LBL_HOMEWORKS_SHORT': 'BTVN',
      'LBL_HOMEWORKS_MORE': 'Bài tập thêm: ',
      'LBL_SHOW_MORE': 'Xem thêm',
      'LBL_SHOW_LESS': 'Thu gọn',
      'LBL_KOC': 'Khóa học',
      'LBL_CLASS_CODE': 'Mã lớp',
      'LBL_CLASS_NAME': 'Tên lớp',
      'LBL_SELECT_CLASS': 'Chọn lớp',
      'LBL_SELECT': 'Chọn',
      'LBL_SELECT_CLASS_SUB': 'Bạn muốn lựa chọn lớp nào?',
      'LBL_START_DATE': 'Khai giảng',
      'LBL_END_DATE': 'Kết thúc',
      'LBL_LESSON_STATUS': 'Trạng thái: ',
      'LBL_TIME': 'Thời gian: ',
      'LBL_SENT_TIME': 'Thời gian gửi',
      'LBL_LESSON_DETAIL': 'Chi tiết buổi học',
      'LBL_FEEDBACK': 'Tạo phản hồi',
      'LBL_YOUR_FEEDBACK': 'DS phản hồi',
      'LBL_YOUR_FEEDBACK_DETAIL': 'Quản lý phản hồi',
      'LBL_CHOOSE_FEEDBACK_TYPE': 'Chưa chọn',
      'LBL_FEEDBACK_TYPE': 'Loại phản hồi',
      'LBL_FEEDBACK_NUMBER': 'Số phản hồi',
      'LBL_FEEDBACK_SUBJECT': 'Chủ đề phản hồi',
      'LBL_FEEDBACK_CONTENT': 'Nội dung phản hồi',
      'LBL_FEEDBACK_CONTENT_HINT': 'Nhập thông tin chi tiết phản hồi',
      'LBL_FEEDBACK_SUBJECT_HINT': 'Nhập tiêu đề phản hồi',
      'LBL_FEEDBACK_TYPE_HINT': 'Vui lòng chọn loại phản hồi ở bên dưới',
      'LBL_SEND': 'Gửi',
      'LBL_GOT_TAGS': 'Gắn thẻ',

      'LBL_HOME_SCHEDULES': 'Lịch học',
      'LBL_HOME_REPORT': 'Sổ liên lạc',
      'LBL_HOME_GRADE_BOOK': 'Kết quả học tập',
      'LBL_HOME_PAYMENT': 'Học phí',
      'LBL_HOME_NEWS': 'Dành cho bạn',
      'LBL_CALENDAR': 'Thời khóa biểu',
      'LBL_LIST': 'Danh sách',
      'LBL_STUDENT_INFO': 'Thông tin học viên',
      'LBL_UNBEGUN': 'Chưa bắt đầu',
      'LBL_CURRENT_PASS': 'Mật khẩu cũ',
      'LBL_NEW_PASS': 'Mật khẩu mới',
      'LBL_CONFIRM_PASS': 'Mật khẩu xác nhận',
      'LBL_CURRENT_PASS_ERROR': 'Mật khẩu hiện tại không đúng',
      'LBL_NEW_PASS_ERROR': 'Mật khẩu mới ít nhất 6 ký tự ',
      'LBL_CONFIRM_PASS_ERROR': 'Mật khẩu xác nhận không khớp',
      'LBL_CONFIRM_PASS_HINT': 'Nhập lại mật khẩu mới',
      'LBL_NEW_NOTIFICATION': 'Bạn có 1 thông báo mới!',
      'LBL_RESULT_OF_EACH_LESSON': 'Kết quả từng buổi học',
      'LBL_INFORMATION_OF_EACH_LESSON': 'Thông tin từng buổi học',
      'LBL_TEACHER_CMT': 'Nhận xét của giáo viên: ',
      'LBL_DO_HOMEWORK': 'Có làm BTVN',
      'LBL_DO_NOT_HOMEWORK': 'Không làm BTVN',
      'LBL_NO_INTERNET': 'Không có kết nối mạng! ',
      'LBL_TRY_AGAIN': 'Thử lại',
      'LBL_NOT_NOW': 'KHI KHÁC',
      'LBL_PAYMENT_DETAIL': 'Chi tiết thanh toán',
      'LBL_NAME': 'Tên: ',
      'LBL_COURSE_FEE': 'Tên khóa học: ',
      'LBL_RECEIPT_CODE': 'Mã thanh toán: ',
      'LBL_METHOD': 'Phương thức thanh toán: ',
      'LBL_RECEIPT_DATE': 'Ngày thanh toán: ',
      'LBL_EXPECTED_RECEIPT_DATE': 'Ngày dự kiến TT: ',
      'LBL_TEAM_NAME': 'Tại trung tâm: ',
      'LBL_LAST_UPDATE': 'Cập nhật lần cuối: ',
      'LBL_REPLIED': 'Đã trả lời',
      'LBL_NOT_REPLIED': 'Chưa trả lời',
      'LBL_CHOOSE_STUDENT': 'Chọn học viên',
      'LBL_MARK_AS_READ': 'Đánh dấu đã xem',
      'LBL_MARK_AS_UNREAD': 'Đánh dấu chưa xem',
      'LBL_DELETE': 'Xóa',
      'LBL_SEND_FEEDBACK_SUCCESS_1': 'Cảm ơn phản hồi của bạn!',
      'LBL_SEND_FEEDBACK_SUCCESS_2': 'Phản hồi của bạn đã được gửi thành công.',
      'LBL_SEND_FEEDBACK_SUCCESS_3': 'Xem chi tiết',
      'LBL_SEND_FEEDBACK_LOADING_1': 'Vui lòng đợi!',
      'LBL_SEND_FEEDBACK_LOADING_2': 'Chúng tôi đang xử lý phản hồi của bạn.',
      'LBL_LOST_CONNECTION_1': 'Lỗi kết nối',
      'LBL_LOST_CONNECTION_2':
          'Không thể kết nối đến máy chủ do các nguyên nhân sau:',
      'LBL_LOST_CONNECTION_3': ' - Thiết bị của bạn không có kết nối mạng.',
      'LBL_LOST_CONNECTION_4': ' - Máy chủ không ổn định ở thời điểm hiện tại.',
      'LBL_LOST_CONNECTION_5':
          'Vui lòng kiểm tra kết nối mạng hoặc thử lại sau ít phút.',
      'LBL_HOME_REPORT_DES':
          'Bạn không nhớ <strong>lịch học, quá trình học</strong> như thế nào? Đừng lo hãy đến đây để xem nhé.',
      'LBL_HOME_PAYMENT_DES':
          'Bạn muốn biết thông tin về <strong>học phí, quá trình đóng tiền</strong> cho Trung tâm, đừng lo bạn có thể xem thông tin ở đây.',
      'LBL_LOGIN_INTRO_3':
          'Bạn có thể tùy ý hiển thị một lớp cuối cùng, trung bình của tất cả các đánh giá, hoặc được cấu hình từ các lớp học sinh trong mỗi thể loại. Bạn thậm chí có thể áp dụng trọng số trên danh mục cho một lớp cuối cùng thực sự tùy chỉnh, cũng như hiển thị trung bình danh mục trong sổ điểm của bạn.',
      'LBL_HOME_GRADE_BOOK_DES':
          '<strong>Kết quả học tập, bảng điểm</strong> của các lớp mà bạn đang học sẽ được chúng tôi cập nhật  liên tục tại đây.',
      'LBL_GALLERY_INTRO':
          'Những <strong>khoảnh khắc, hình ảnh</strong> của bạn với Trung tâm của chúng tôi được lưu giữ ở đây.',
      'LBL_TOUR_SWITCH_USER': 'Đổi học viên',
      'LBL_TOUR_SWITCH_USER_CONTENT':
          'Nếu bạn là <strong>phụ huynh có hai bé trở lên</strong> đang học tại Trung tâm của chúng tôi. Bạn hãy chọn biểu tượng hai mũi tên ở trên để xem thông tin của từng bé.',
      'LBL_TOUR_NEWS': 'Dành cho bạn',
      'LBL_TOUR_NEWS_CONTENT':
          ' Tính năng để xem tin tức về trường bao gồm, các sự kiện diễn ra trong trường, cũng có thể nhận được thông báo định kỳ về thông báo của bất kỳ sự kiện nào do trường tiến hành.',
      'LBL_CURRENT_PASS_HINT': 'Nhập mật khẩu hiện tại',
      'LBL_NEW_PASS_HINT': 'Nhập mật khẩu mới',
      'LBL_LESSON': 'Buổi',
      'LBL_RATE_DONE': 'Đánh giá thành công',

      'LBL_RATING_LESSON_1': 'Đánh giá buổi học ',
      'LBL_RATING_FEEDBACK_1': 'Đánh giá phản hồi ',
      'LBL_RATING_CLASS_1': 'Đánh giá lớp học ',
      'LBL_RATING_LESSON_2': 'Chọn điểm từ 1 đến 5 sao',
      'LBL_RATING_LESSON_3': 'Nội dung đánh giá',
      'LBL_NO_DATA_AVAILABLE': 'Không tìm thấy dữ liệu.',
      'LBL_NO_DATA_AVAILABLE_FEEDBACK': 'Bạn chưa gửi phản hồi nào',
      'LBL_NO_DATA_AVAILABLE_DOCUMENT': 'Không có tài liệu',
      'LBL_NO_DATA_AVAILABLE_LOYALTY': 'Bạn chưa có điểm tích lũy',
      'LBL_NO_DATA_AVAILABLE_GALLERY': 'Không có hình ảnh',
      'LBL_NO_DATA_AVAILABLE_PAYMENT': 'Không có thanh toán',
      'LBL_NO_DATA_AVAILABLE_NOTI': 'Không có thông báo mới',
      'LBL_DESCRIPTION': 'Ghi chú',
      'LBL_LMS': 'Ứng dụng LMS',
      'LBL_SHARE_PHOTO': 'Chia sẽ',
      'LBL_DOWNLOAD_PHOTO': 'Tải về',
      'LBL_IMAGE': 'Hình ảnh',
      'LBL_MESSAGE': 'Tin nhắn',
      'LBL_STUDENT_TYPE': 'Loại học viên',
      'LBL_TYPE': 'Loại',
      'LBL_ATTENDANCE_DO_HOMEWORK': 'BTVN đã giao:',
      'LBL_ATTENDANCE_LOYALTY_POINT': 'Điểm thưởng',
      'LBL_ATTENDANCE_DAILY_SCORE': 'Điểm đánh giá',
      'LBL_ATTENDANCE_CARE_COMMENT': 'Nhận xét của trợ giảng',
      'LBL_CONFIRM_NAVIGATION': 'Xác nhận rời khỏi',
      'LBL_CONFIRM_NOTIFICATION': 'Xác nhận gửi thông báo',
      'LBL_CONFIRM_NOTIFICATION_CONTENT':
          'Bạn có chắc là muốn gửi thông báo đến học viên không?',
      'LBL_CONFIRM_NAVIGATION_CONTENT': 'Bạn có chắc là muốn rời khỏi không?',
      'LBL_DIALOG_NO': 'Không',
      'LBL_DIALOG_YES': 'Có',

      // List String
      'Male': 'Nam',
      'Month': 'Tháng',
      'Week': 'Tuần',
      'Female': 'Nữ',
      'Monday': 'Thứ hai',
      'Tuesday': 'Thứ ba',
      'Wednesday': 'Thứ tư',
      'Thursday': 'Thứ năm',
      'Friday': 'Thứ sáu',
      'Saturday': 'Thứ bảy',
      'Sunday': 'Chủ nhật',
      'not_stated': 'Chưa học',
      'in_progress': 'Đang diễn ra',
      'finished': 'Đã học',
      'P': 'Có đi học',
      'L': 'Đi học trễ',
      'A': 'Vắng có phép',
      'E': 'Vắng không phép',
      'none': 'Không có',
      'Unpaid': 'Chưa thanh toán',
      'Paid': 'Đã thanh toán',
      'Cash': 'Tiền mặt',
      'Card': 'Thẻ',
      'Bank Transfer': 'Chuyển khoản',
      'Other': 'Khác',
      'invalid_username': 'Số điện thoại không đúng',
      'invalid_code': 'Mã xác nhận không đúng',
      "SUN": 'CN',
      "MON": 'T2',
      "TUE": 'T3',
      "WED": 'T4',
      "THU": 'T5',
      "FRI": 'T6',
      "SAT": 'T7',
      // Notification
      'LBL_CHANGE_PASS_SUCCESS': 'Thay đổi mật khẩu thành công!',
      'LBL_TAP_TO_EXIT': 'Nhấn quay lại lần nữa để thoát',
      'LBL_CALL_HOTLINE': 'Gọi ngay',

      'LBL_CHANGE_PASS_FAIL': 'Thay đổi mật khẩu thất bại!',
      'LBL_GALLERY': 'Thư viện ảnh',
      //'LBL_CLASS_PROGRESS_TEXT': 'buổi đã kết thúc',
      'LBL_CLASS_PROGRESS_TEXT': 'buổi',
      'LBL_TEACHER_REVIEW': 'GV Đánh giá',
      'LBL_TEACHER_ATTENDANCE': 'Điểm danh',
      'LBL_NAME_ATTENDANCE': 'Tên học viên',

      // Reuquest update
      'LBL_IGNORE': 'Bỏ qua',
      'LBL_LATER': 'Để sau',
      'LBL_UPDATE_NOW': 'Cập nhật',
      'LBL_PROMT':
          'Ứng dụng đã có phiên bản mới! Bạn có muốn cập nhật ngay bây giờ không?',
      'LBL_TITLE_UPDATE': 'Cập nhật ứng dụng?',

      // Settings
      'LBL_SETTINGS': 'Cài đặt',
      'LBL_COMMON': 'Chung',
      'LBL_LANGUAGES': 'Ngôn ngữ',
      'LBL_INFO': 'Thông tin',
      'LBL_EMAIL': 'Email',
      'LBL_SIGN_OUT': 'Đăng xuất',
      'LBL_SECURITY': 'Bảo mật',
      'LBL_FINGER': 'Sử dụng vân tay để mở khóa',
      'LBL_CHANGE_PASSWORD': 'Đổi mật khẩu',
      'LBL_MISC': 'Nhiều hơn',
      'LBL_TERMS': 'Điều khoản dịch vụ',
      'LBL_LICENSES': 'Giấy phép',
      'LBL_CURRENT_LANG': 'Tiếng Việt',
      'LBL_CAMERA': 'Máy ảnh',
      'LBL_RATE': 'Đánh giá khoá học:',

      //Pull to refresh
      'LBL_PULL_TO_REFRESH': 'Kéo xuống để làm mới',
      'LBL_RELEASE_TO_REFRESH': 'Thả để làm mới',
      'LBL_REFRESHING': 'Đang làm mới',
      'LBL_COMPLETED_REFRESH': 'Hoàn tất',
      'LBL_CENTER_NAME': 'Tên trung tâm',

      'Finished': 'Kết thúc',
      'In Progress': 'Đang diễn ra',
      'LBL_NON_SUBJECT': 'Không có tên bài học!',
      'LBL_INFOR_LESSON': 'Thông tin lịch học',
      'LBL_NO_DATA_LESSON': 'Không có lịch học!',
      'LBL_ALBUM_DESCRIPTION': 'Bạn nghĩ gì về album này?',
      'LBL_CONFIRM_NAVIGATION': 'Hủy bỏ thay đổi',
      'LBL_NO_NAVIGATION': 'Tiếp tục sửa',
      'LBL_CONFIRM_NAVIGATION_CONTENT_CREATE':
          'Bạn có chắc chắn muốn hủy bỏ dữ liệu mới này không?',

      'LBL_RESEND_CODE': 'Gửi lại',
      'LBL_TIME_LIMIT_CODE': 'Mã sẽ hết hạn sau',
      'LBL_ENTER_NEW_PASSWORD': 'Thiết lập mật khẩu',
      'LBL_ENTER_CODE_VERIFICATION': 'Mã xác minh của bạn đã được gửi tới',
      'LBL_PLEASE_WAIT_CODE': 'Vui lòng đợi',
      'LBL_SEND_CODE_BACK': 'giây để gửi lại.',
      'LBL_NOT_RECEIVE_CODE': 'Bạn không nhận được mã?',
      'LBL_NEXT': 'Tiếp',
      'LBL_OR_TRY': 'hoặc thử',
      'LBL_CONTACT_CENTER': 'liên hệ với trung tâm',
      'LBL_POLICY_PASSWORD': 'Mật khẩu phải từ 6 đến 16 ký tự.',
      'LBL_CHANGE_PASS_DONE': 'Đổi mật khẩu thành công',
      'AM': 'sáng',
      'PM': 'chiều',
      'LBL_SAVE_DONE': 'Lưu thành công!',

      //Loyalty
      'LBL_PAYMENT_NAME': 'Hoá đơn',
      'LBL_DESCRIPTION_LOYALTY': 'Ghi chú',
      'LBL_ACCUMULATION': 'Lịch sử tích điểm',

      'LBL_MENU_HOME_INTRO':
          'Bạn có thể chọn vào đây để quay lại <strong>màn hình chính</strong> của ứng dụng.',
      'LBL_MENU_FEEDBACK_INTRO':
          'Bạn có thể <strong>xin nghỉ phép, hỏi về học phí, lịch học</strong> hoặc các <strong>thắc mắc</strong> tại đây.',
      'LBL_DOCUMENT_INTRO':
          'Bạn có thể <strong>xem tài liệu, file nghe, file video</strong> tại đây.',
      'LBL_MENU_PROFILE_INTRO':
          'Bạn có xem và cập nhật một số <strong>thông tin cá nhân</strong> tại đây.',

      //Attendance
      'LBL_SELECT_SEND_NOTIFICATIONS': 'Send notifications',
      'LBL_EXCUSED': 'Vắng KP',
      'LBL_SEND_NOTIFICATIONS': 'Thông báo',
      'LBL_SENT': 'Đã gửi',
      'LBL_SENDING': 'Đang gửi',
      'LBL_PUSH_NOTIFICATIONS': 'Gửi thông báo',
      'LBL_CHECK_ALL': 'Chọn tất cả',
      'LBL_LOGOUT_TITLE': 'Bạn có muốn đăng xuất không?',
      'LBL_LOGOUT_CONTENT':
          'Đăng xuất sẽ xóa mọi dữ liệu đã lưu trong bộ nhớ đệm.',
      'LBL_ABSENT': 'Vắng',
      'LBL_JUSTIFIED': 'Có phép',
      'LBL_UNJUSTIFIED': 'Không phép',
      'LBL_MARK_ALL': 'Chọn tất cả',
      'LBL_UNCHECK': 'Không',
      'LBL_PRESENT': 'Có mặt',
      'LBL_LATE': 'Trễ',
      'LBL_A_JUSTIFIED': 'Vắng Có phép',
      'LBL_A_UNJUSTIFIED': 'Vắng Không phép',
      'LBL_TOTAL': 'Tổng cộng',

      //Gallery
      'LBL_DOWNLOAD': 'Tải về máy',
      'LBL_CLASS': 'Lớp',
      'LBL_CLASSES': 'Tổng quan lớp',
      'LBL_SHARE': 'Chia sẽ',
      'LBL_PHOTO': 'ảnh',
      'LBL_PHOTOS': 'ảnh',
      'LBL_ADDED': 'đã thêm',
      'LBL_DOWNLOAD_DONE': 'Tải xuống thành công',
      'LBL_DOWNLOAD_FAIL': 'Đã xảy ra lỗi',
      'LBL_ALBUM': 'album',
      'LBL_TO': 'vào',
      'LBL_CREATE_ALBUM': 'Tạo album ảnh',
      'LBL_ALBUM_NAME': 'Tên album',
      'LBL_SEARCH': 'Tìm kiếm',
      'LBL_POSTING_1': 'Có 1 album đăng bài về hashtag này',
      'LBL_POSTING_N': 'albums đăng bài về hashtag này',

      //Home
      'LBL_NO_FEATURED_POST': 'Chưa có bài viết nổi bật',
      'All': 'Tất cả',
      'Feedback': 'Tin nhắn',
      'Classes': 'Học vụ',
      'LBL_TOOLKIT': 'Công cụ',
      'LBL_SYLLABUS': 'Giáo trình',
      'LBL_EXAM': 'Bài tập',

      //Profile
      'LBL_CONFIRM': 'Xác nhận',
      'LBL_SEE_MORE': 'Xem thêm',
      'LBL_PERSONAL_SETTINGS': 'Cài đặt trang cá nhân',
      'LBL_UPDATE_AVATAR': 'Chỉnh sửa ảnh đại diện',
      'LBL_UPDATE_COVER': 'Chỉnh sửa ảnh bìa',
      'LBL_UPDATE_INFORMATION': 'Chỉnh sửa thông tin cá nhân',
      'userInfo': 'Thông tin tài khoản',

      //Class
      'LBL_IN_PROGRESS': 'Đang diễn ra',
      'LBL_FINISHED': 'Đã kết thúc',
      'LBL_OVERVIEW': 'Tổng quan',
      'LBL_SCHEDULE': 'Lịch học',
      'LBL_PROGRESS': 'Tiến độ',

      // Drawer
      'LBL_STUDENT_LIST': 'Chọn học viên',
    };
  }

  _buildLangEn() {
    return {
      // Menu
      'navHome': 'Home',
      'navStore': 'Store',
      'navNotify': 'Notification',
      'userNav': 'Account',
      'yourOrderNav': 'Your orders',
      'aboutNav': 'About us',
      'contactNav': 'Contact',
      'operationNav': 'Operation Regulation',
      'termNav': 'Terms and Services',
      'privacyNav': 'Privacy Policy',
      'shippingInfoNav': 'Shipping Info',
      'payInstructNav': 'Payment Instruction',
      'discountNav': 'Offer',
      'plantFeature': 'Bác sĩ tư vấn',
      'productTop': 'Bác sĩ khuyên dùng',

      // Common
      'welcomeToApp': 'Welcome to BacSiCayXanh',
      'or': 'Or',
      'phoneInput': 'Input your phone number',
      'continue': 'Continue',
      'search': 'Search',
      'checkout': 'Checkout',
      'viewdetail': 'View detail',
      'buyagain': 'Buy again',
      'all': 'All',
      'allProduct': 'All Products',
      'customer': 'Customer',
      'verified': 'Verified',
      'anonymous': 'Anonymous',
      'logout': 'Sign out',
      'notLogin': 'Not login yet',
      'orderDetail': 'Order detail',
      'shippingaddress': 'Shipping address',
      'productlist': 'Product list',
      'paymentmethod': 'Payment method',
      'fullName': 'Full name',
      'phoneNumber': 'Phone number',
      'save': 'Save',
      'review': 'Review',
      'instruction': 'Instruction',
      'sort': 'Sort',
      'showMore': 'Show more',
      'showLess': 'Show less',
      'week': 'Week',
      'day': 'Day',
      'completed': 'Completed',
      'onGoing': 'Ongoing',
      'upNext': 'Up next',
      'nextStep': 'Next step',
      'goBack': 'Go back',
      'discoveryTag': 'Discovery Subject',
      'newsTop': 'Top news',
      'yes': 'Yes',
      'no': 'No',
      'commentInput': 'Your comment',
      'selectPlant2': 'Select Plant',
      'news': 'News',
      'goBackHome': 'Trở về trang chủ',
      'thankYou': 'Cảm ơn bạn!',
      'processingYourOrder': 'Đơn hàng của bạn đang được xử lý',
      'cancel': 'Huỷ',


      //comment
      'loginToComment': 'Hãy đăng nhập để tham gia bình luận',
      'postComment': 'Đăng bình luận',
      'pleaseTryAgainInMinutes': 'Bạn mới đăng bình luận gần đây, xin vui lòng thử lại trong ít phút nữa',
      'postCommentSuccess': 'Đã đăng bình luận thành công',
      'mustLarge15Letters': 'Bạn phải nhập lớn hơn 15 ký tự',
      'larger15AndLeast150Letters':'Nhập lớn hơn 15 và nhỏ hơn 150 ký tự',
      'writeComment': 'Viết bình luận',
      'noComment': 'Hiện không có bình luận nào',
      'confirmDeleteComment':'Bạn có muốn xóa bình luận này không?',
      'deleteComplete':'Đã xóa thành công',
      'commentMore':'Xem thêm bình luận',


      //Discount
      'selectDiscount': 'Select discount code',
      'apply': 'Apply',
      'inputVoucher': 'Input voucher',
      'check': 'Kiểm tra',
      'canChoose': 'Có thể chọn',
      'chooseOrInputCoupon': 'Chọn hoặc nhập mã khuyến mãi',
      'discountApplied': 'Khuyến mãi đang áp dụng',
      'emptyCoupon': 'Chưa chọn mã',
      'hadChosen': 'mã đã chọn',

      // Sort
      'CreateOnDesc': 'Newest',
      'PriceAsc': 'Price low to high',
      'PriceDesc': 'Price high to low',
      'NameAsc': 'Name A->Z',
      'NameDesc': 'Name Z->A',
      'DEFAULT': 'Mặc định',
      'CREATE_ON_ASC': 'Cũ nhất',
      'CREATE_ON_DESC': 'Mới nhất',
      'PRICE_ASC': 'Giá tăng dần',
      'PRICE_DESC': 'Giá giảm dần',
      'NAME_ASC': 'Tên A->Z',
      'NAME_DESC': 'Tên Z->A',

      // Plant
      'blog': 'Blog',
      'technique': 'Technique',
      'bug': 'Bug',
      'disease': 'Disease',
      'nutrition': 'Nutrition',
      'beforeSow': 'before sow',
      'selectYourPlant': 'Select your plant',
      'plantAlreadySelected': 'Plant already selected',
      'canBeFound': 'Can be found in',
      'symptomMsg': 'Symptoms',
      'treatNow': 'Treat now',
      'precaution': 'Precaution',
      'treatProduct': 'Treat with product',
      'diseaseReason': 'Reason',
      'recognize': 'Đặc điểm nhận biết',
      'consequence': 'Consequence',
      'sowDay': 'Sow day',
      'plantInfoUpdating': 'Plant info is updating',
      'fieldSupervision': 'Field supervision',
      'diseaseCanHave': 'These diseases can appear on your crops',
      'pestCanHave': 'These pests can appear on your crops',
      'tips': 'Tips',
      'task': 'Task',
      'selectPlant': 'Select plant',
      'useProduct': 'useProduct',
      'otherDisease': 'Bệnh khác của cây',
      'otherPest': 'Sâu khác có thể gặp ở cây',
      'otherPost': 'Bài viết liên quan',
      'plantBlog': 'Bài viết cây trồng',
      'productIsUpdating': 'Danh sách sản phẩm đang được cập nhật',
      'searchPlant': 'Tìm cây bạn muốn trồng',

      //author
      'authorInfo': 'Thông tin tác giả',

      //info
      'companyInfo': 'Công Ty TNHH Nông Nghiệp Công Nghệ Cao',
      'taxCode': 'Mã số thuế: ',
      'taxCodeBy': 'Do Sở Kế Hoạch và Đầu Tư Hà Tĩnh cấp lần đầu ngày 26/05/2017, cập nhật thay đổi vào ngày 04/12/2018',
      'productCertificate': 'Giấy chứng nhận đủ điều kiện sản xuất phân bón',
      'certificateNumber':'Số: 01 GCN/TTr - BVTV - PB, do Chi cục trồng trọt và bảo vệ thực vật Hà Tĩnh cấp ngày 3 tháng 10 năm 2019',
      'contactInfo': 'Thông tin liên hệ:',
      'contactAddress': 'Lô CN12, Cụm khu công nghiệp Phù Việt, Xã Phù Việt, Huyện Thạch Hà, Tỉnh Hà Tĩnh, VN',

      // Notify

      //Contact us
      'contactUs': 'Contact us',
      'email': 'Email',
      'company': 'Company',
      'message': 'Message',
      'content': 'Content',
      'sendFeedback': 'Send feedback',
      'personalinfo': 'Thông tin cá nhân',
      'entervalidemail': 'Enter a valid email address',
      'sentContact': 'Sent successfully!',

      // Error
      'errorMsg': 'Something went wrong, please try again!',
      'inputErrorMsg': 'Please input value!',
      'infoFoundErrorMsg': 'No information found!',
      'phoneNotValid': 'Phone number is not correct!',
      'infoNotFound': 'Not found what you looking for, please get back later!',

      // Review Order
      'reviewOrder': 'Review order',
      'writeReview': 'Viết đánh giá...',
      'sendReview': 'Gửi đánh giá',
      'reviewDone': 'Đã đánh giá',

      // Order
      'emptyOrderHistory': 'No order found!',
      'cancelOrder': 'Cancel order',
      'receiveOrder': 'Receive order',
      'emptyOrders': 'No orders found!',
      'orderStatusFollow': 'Order status',
      'Pending': 'Pending',
      'Processing': 'Processing',
      'Complete': 'Shipping',
      'ReceivedConfirmed': 'Received',
      'Cancelled': 'Cancelled',

      // QR
      'qrScan': 'Scan QR Code',
      'qrScanMsg': 'Please place the QR code in front of the camera',
      'qrInstructionMsg':
          'QR code look like this and usually is printed on the label',
      'qrScanErrorMsg': 'QR code is not valid please try again!',

      // Address
      'shippingAddress': 'Shipping address',
      'addAddress': 'Add address',
      'editAddress': 'Edit address',
      'contactHint': 'Contact info',
      'address': 'Address',
      'streetHint': 'Building name, street name',
      'stateHint': 'State',
      'districtHint': 'District',
      'townHint': 'Town',
      'isSetDefaultAddress': 'Do you want to set to default?',

      // Payment
      'paymentMethod': 'Payment method',
      'shipCodeMsg': 'Pay on receive',

      // Checkout
      'yourOrderItems': 'Your order',
      'subTotal': 'Subtotal',
      'total': 'Total',
      'totalIncludeVAT': 'Total (Incl. VAT)',
      'includeVAT': 'Đã bao gồm VAT nếu có',
      'totalPrice': 'Thành tiền',
      'shippingFee': 'Shipping fee',
      'discountTotal': 'Discount',
      'discountPrice': 'Giảm giá',
      'share': 'Share',
      'completePayment': 'Complete payment',
      'lastPaymentInfo': 'Các thông tin khác',
      'agreementMsg': 'By making this purchase you agree to our',
      'agreementPrivacy': 'Bằng việc đăng ký, bạn đồng ý với',
      'agreementPrivacyExpand': ' của chúng tôi',
      'proceedCheckout': 'Proceed to checkout',
      'confirmCancelOrder': 'Bạn có chắc muốn hủy đơn hàng?',
      'noteOrderCheckout': 'Ghi chú đơn hàng',
      'orderBuy': 'Đặt mua',

      // Sign In
      'login': 'Login',
      'loginOrRegister': 'Đăng nhập hoặc đăng kí',
      'loginFacebook': 'Login with Facebook',
      'loginGoogle': 'Login with Google',
      'inputOtp': 'Input OTP',
      'inputOtpAuth': 'Input OTP to verify order',
      'otpSentTo': 'OTP code has been sent to this number ',
      'otpTimeLast': 'OTP effective in',
      'sendAgain': 'Send again',
      'sendAgainAfter': 'Try again after ',
      'checkPhoneNumber': 'Your phone number is not valid!',
      'otpInvalid': 'OTP code invalid!',
      'otpCode': 'OTP Code',
      'getOtpCode': 'Get Code',
      'accountUseDifferent':
          'Account is use with an other different login method!',
      'otpSuccess': 'OTP Success',

      // Product
      'productNotFound': 'Product not found!',
      'productItem': 'Item',
      'relatedProduct': 'Related product',
      'buy': 'Buy',
      'buyNow': 'Buy Now',
      'addToCard': 'Add To Card',
      'add': 'Add',
      'contentIsUpdating': 'Content is being updated!',
      'imageIsUpdating': 'Image is being updated!',
      'filterDone': 'Filter products',
      'filterPrice': 'By price',
      'orderBy': 'Order by',
      'productCategory': 'Product category',
      'productsEmpty': 'No product found',
      'productTag': 'Tags',
      'productDescription': 'Product Description',
      'userGuide': 'User Guide',
      'ratingProduct': 'Rating Product',
      'reviewIn': 'Review in',
      'crossSell': 'Cross Sell',
      'moreFromCustomer': 'More picture from customers',
      'close': 'Close',
      'quantity': 'Quantity',
      'freeshipAmount': 'Freeship đơn hàng từ 200k',
      'buyLargeGoodCost': 'Mua sỉ giá tốt',
      'shipByDay': 'Nhận hàng sau 2 - 4 ngày',
      'addProduct': 'Thêm sản phẩm',
      'addProductSuccess': 'Thêm vào giỏ hàng thành công',
      'deleteCrossSellProduct': 'Đã xóa sản phẩm khỏi giỏ hàng',

      // Cart
      'emptyBag': 'No item selected',
      'confirmDeleteItem': 'Bạn có chắc muốn xóa sản phẩm này?',
      'confirmDeleteAddress': 'Bạn có chắc muốn xóa địa chỉ này?',
      'confirmSignOut': 'Bạn có chắc muốn đăng xuất?',

      // Label
      '': '',
      'LOGIN': 'LOGIN',
      'OK': 'OK',
      'You': 'You',

      'Unpaid': 'Unpaid',
      'Paid': 'Paid',
      'Last reply on': 'Last reply on',

      'LBL_GOT_TAGS': 'Got Tags?',
      'Your profile image was updated!': 'Your profile image was updated!',
      'LBL_SLIDE_1':
          'Connecting parents / students with school / teachers, interacting and communicating easily anytime, anywhere.',
      'LBL_SLIDE_2':
          'A dedicated educational social network that allows parents to conveniently keep track of students\'s daily activities in the classroom.',
      'LBL_SLIDE_3':
          'Continuously update comments and assessments of teachers after each lesson. Easily track your study progress, homework.',
      'LBL_SLIDE_4':
          'And there are many impressive and attractive features which are regularly updated by DotB. Bring out the best experience for you.',

      'Schedules reminder': 'Schedules reminder',
      'LBL_REMINDER_AT_1': 'Ứng dụng sẽ gửi một thông báo nhắc nhở ',
      'LBL_REMINDER_AT_2': ' phút trước buổi học.',
      'Update App': 'Update App',
      'LBL_UPDATE_PROMPT_OLD1': 'A new version',
      'LBL_UPDATE_PROMPT_OLD2': 'is available!',
      'LBL_UPDATE_PROMPT': 'Would you like to update it now?',
      'LBL_UPDATE_BUTTON_TITLE': 'Update Now',
      'Today': 'Today',
      'Attach Image': 'Attach Image',
      'LBL_CONTENT_AT_LEAST': 'The feedback content must not be empty.',
      'LBL_TITLE_AT_LEAST': 'The feedback subject must not be empty.',
      'LBL_LOGIN_FAIL': 'Login fail',
      'LBL_LOGIN_AS_TEACHER': 'Teacher login is coming soon',
      'Incorrect username or password': 'Incorrect username or password',
      'LBL_SUCCESS': 'Success',
      'Version': 'Version: ',
      'LBL_SELECT_LANG': 'Language: ',
      'Forgot password?': 'Forgot password?',
      'Enter your email address to request a password reset.':
          'Enter your email address to request a password reset.',
      'LBL_ENTER_CODE': 'Enter your verify code to reset password.',
      'LBL_FEEDBACK_LIST': 'Feedback list',
      'LBL_MENU_HOME': 'Home',
      'LBL_MENU_CALENDAR': 'Calendar',
      'LBL_HOME_ATTENDANCE': 'Attendance',
      'LBL_DATE_ATTENDANCE': 'Attendance date',
      'LBL_MENU_PAYMENT': 'Payment',
      'LBL_MENU_PROFILE': 'Profile',
      'LBL_MENU_FEEDBACK': 'Feedback',
      'LBL_DOCUMENT': 'Document',
      'LBL_EMAIL_ADDRESS': 'Email',
      'LBL_PASSWORD': 'Password',
      'LBL_CHANGE_PASSWORD': 'Change password',
      'LBL_GENDER': 'Gender',
      'LBL_USERNAME_EMAIL': 'Username/ Email',
      'LBL_BIRTHDATE': 'Birthdate',
      'LBL_ID': 'Student ID',
      'Please wait for a while!': 'Please wait for a while!',
      'LBL_STATUS': 'Status',
      'LBL_LOGOUT': 'Logout',
      'LBL_PHONE': 'Phone number',
      'LBL_CHANGE_LANGUAGE': 'Change language',
      'LBL_SUB_CHANGE': 'Which language do you prefer?',

      'LBL_SELECT_CLASS': 'Select class',
      'LBL_SELECT': 'Select',
      'LBL_SELECT_CLASS_SUB': 'Which class do you want?',
      'LBL_CHANGE_USER': 'Switch user',
      'LBL_SUB_CHANGE_USER': 'Which user do you want?',
      'LBL_QR_CODE': 'QR Code',
      'LBL_NICKNAME': 'Nick name',
      'LBL_SCORE': 'Loyalty point',
      'LBL_SCORE_HISTORY': 'Loyalty',
      'LBL_AMOUNT': 'Amount: ',
      'LBL_SAVE': 'Save',
      'LBL_SAVE_LIST': 'Save list',
      'LBL_SAVE_AND_SEND_NOTI': 'Save & Push Noti',
      'LBL_CANCEL': 'Cancel',
      'LBL_SUBMIT': 'SEND',
      'LBL_NOTIFICATIONS': 'Notifications',
      'LBL_TOPIC': 'Topic: ',
      'LBL_ACTIVITIES': 'Main Activities: ',
      'LBL_HOMEWORK': 'Homeworks: ',
      'LBL_HOMEWORKS_SHORT': 'Homeworks',
      'LBL_HOMEWORKS_MORE': 'More homework: ',
      'LBL_SHOW_MORE': 'Show more',
      'LBL_SHOW_LESS': 'Show less',
      'LBL_KOC': 'Course',
      'LBL_CLASS_CODE': 'Class code',
      'LBL_CLASS_NAME': 'Class name',
      'LBL_START_DATE': 'Start date',
      'LBL_END_DATE': 'End date',
      'LBL_ALBUM_DESCRIPTION': 'What do you think about this album?',
      'LBL_CONFIRM_NAVIGATION': 'Discard Changes',
      'LBL_NO_NAVIGATION': 'Keep Editing',
      'LBL_CONFIRM_NAVIGATION_CONTENT_CREATE':
          'Are you sure you want to discard this new record?',

      'LBL_LESSON_STATUS': 'Status: ',
      'LBL_RATE_DONE': 'Rate successfully',
      'LBL_TIME': 'Dates/Times: ',
      'LBL_SENT_TIME': 'Dates/Times',
      'LBL_LESSON_DETAIL': 'Lesson detail',
      'LBL_FEEDBACK': 'Feedback',
      'LBL_YOUR_FEEDBACK': 'Your Feedbacks',
      'LBL_YOUR_FEEDBACK_DETAIL': 'Manage your feedback',
      'LBL_CHOOSE_FEEDBACK_TYPE': 'None',
      'LBL_FEEDBACK_TYPE': 'Feedback Type',
      'LBL_FEEDBACK_NUMBER': 'Feedback number',
      'LBL_FEEDBACK_SUBJECT': 'Feedback subject',
      'LBL_FEEDBACK_CONTENT': 'Feedback content',
      'LBL_FEEDBACK_CONTENT_HINT': 'Enter your feedback content',
      'LBL_FEEDBACK_SUBJECT_HINT': 'Enter your feedback subject',
      'LBL_FEEDBACK_TYPE_HINT':
          'Please select the type of feedback this headline belongs to',
      'LBL_SEND': 'Send',
      'LBL_HOME_SCHEDULES': 'Class schedule',
      'LBL_HOME_REPORT': 'Daily reports',
      'LBL_HOME_GRADE_BOOK': 'Grade book',
      'LBL_HOME_PAYMENT': 'Payment',
      'LBL_HOME_NEWS': 'News',
      'LBL_CALENDAR': 'Calendar',
      'LBL_LIST': 'List',
      'LBL_STUDENT_INFO': 'Student info',
      'LBL_UNBEGUN': 'Unbegun',
      'LBL_CURRENT_PASS': 'Current Password',
      'LBL_NEW_PASS': 'New Password',
      'LBL_CONFIRM_PASS': 'Confirm password',
      'LBL_CONFIRM_PASS_HINT': 'Retype new password',

      'LBL_CURRENT_PASS_ERROR': 'Incorrect current password',
      'LBL_NEW_PASS_ERROR': 'Password must be at least 6 characters',
      'LBL_CONFIRM_PASS_ERROR':
          'Your password and confirmation password do not match',

      'LBL_NEW_NOTIFICATION': 'You have a new notification!',
      'LBL_RESULT_OF_EACH_LESSON': 'Results of each lesson',
      'LBL_INFORMATION_OF_EACH_LESSON': 'Information of each lesson',
      'LBL_TEACHER_CMT': 'Teacher\'s comment: ',

      'LBL_DO_HOMEWORK': 'Do homework',
      'LBL_DO_NOT_HOMEWORK': 'Do not homework',
      'LBL_NO_INTERNET': 'No Internet Connection! ',
      'LBL_TRY_AGAIN': 'Try again',
      'LBL_NOT_NOW': 'NOT NOW',

      'LBL_PAYMENT_DETAIL': 'Payment detail',
      'LBL_NAME': 'Name: ',
      'LBL_COURSE_FEE': 'Course: ',
      'LBL_RECEIPT_CODE': 'Receipt code: ',
      'LBL_METHOD': 'Receipt method: ',
      'LBL_RECEIPT_DATE': 'Receipt date: ',

      'LBL_EXPECTED_RECEIPT_DATE': 'Expected receipt date: ',
      'LBL_TEAM_NAME': 'Center: ',
      'LBL_LAST_UPDATE': 'Last updated: ',
      'LBL_REPLIED': 'Replied',
      'LBL_NOT_REPLIED': 'Not Replied',
      'LBL_CHOOSE_STUDENT': 'Choose Student',
      'LBL_MARK_AS_READ': 'Mark as read',
      'LBL_MARK_AS_UNREAD': 'Mark as unread',
      'LBL_DELETE': 'Delete',
      'LBL_SEND_FEEDBACK_SUCCESS_1': 'Thank you for your feedback!',
      'LBL_SEND_FEEDBACK_SUCCESS_2':
          'Your feedback has been sent successfully.',
      'LBL_SEND_FEEDBACK_SUCCESS_3': 'Go detail',
      'LBL_SEND_FEEDBACK_LOADING_1': 'Please wait!',
      'LBL_SEND_FEEDBACK_LOADING_2': 'We are processing your request.',
      'LBL_LOST_CONNECTION_1': 'Lost connection',
      'LBL_LOST_CONNECTION_2':
          'Could not connect to server due to the following reasons:',
      'LBL_LOST_CONNECTION_3': ' - Your device has no network connection.',
      'LBL_LOST_CONNECTION_4':
          ' - The server is not stable at the present time.',
      'LBL_LOST_CONNECTION_5':
          'Please try checking the network connection or try again in a few minutes.',
      'LBL_HOME_REPORT_DES':
          'You do not remember <strong>the schedule, the learning process</strong>? Don\'t worry, come here to see it.',
      'LBL_HOME_PAYMENT_DES':
          'You would like to know more about <strong>tuition fees, payment process</strong>. Please get the information right here.',
      'LBL_LOGIN_INTRO_3':
          'You can optionally display a final grade, either an average of all assessments, or configured from the student grades in each category. You can even apply weightings on the category for a truly customized final grade, as well as displaying the category averages in your gradebook.',
      'LBL_HOME_GRADE_BOOK_DES':
          'The <strong>academic results, transcripts</strong> of the classes you are studying, are continually updated here.',
      'LBL_GALLERY_INTRO':
          'Your <strong>moments, photos</strong> with our Center are kept here.',
      'LBL_TOUR_SWITCH_USER': 'Switch user',
      'LBL_TOUR_SWITCH_USER_CONTENT':
          'If you are a <strong>parent role with two or more children</strong> studying at our Center. Please select the two arrow icons above to exchange information for each one.',
      'LBL_TOUR_NEWS': 'My School',
      'LBL_TOUR_NEWS_CONTENT':
          'To view the school news including, the events taken place in the school, also can receive periodical alerts of invitations of any events conducting by the school.',
      'LBL_CURRENT_PASS_HINT': 'Type current password',
      'LBL_NEW_PASS_HINT': 'Type new password',
      'LBL_LESSON': 'Lesson',
      'LBL_RATING_LESSON_1': 'Lesson Rating ',
      'LBL_RATING_FEEDBACK_1': 'Feedback Rating ',
      'LBL_RATING_CLASS_1': 'Class Rating  ',
      'LBL_RATING_LESSON_2': 'Select a rating — from one to five stars',
      'LBL_RATING_LESSON_3': 'Comment',
      'LBL_NO_DATA_AVAILABLE': 'No data available',
      'LBL_NO_DATA_AVAILABLE_FEEDBACK': 'No feedback',
      'LBL_NO_DATA_AVAILABLE_DOCUMENT': 'No documents',
      'LBL_NO_DATA_AVAILABLE_LOYALTY': 'Your loyalty is empty',
      'LBL_NO_DATA_AVAILABLE_GALLERY': 'No images',
      'LBL_NO_DATA_AVAILABLE_PAYMENT': 'No payments',
      'LBL_NO_DATA_AVAILABLE_NOTI': 'Have no new notifications',
      'LBL_DESCRIPTION': 'Note',
      'LBL_LMS': 'LMS Application',
      'LBL_SHARE_PHOTO': 'Share Photo',
      'LBL_DOWNLOAD_PHOTO': 'Download Photo',
      'LBL_IMAGE': 'Image',
      'LBL_MESSAGE': 'Message',
      'LBL_STUDENT_TYPE': 'Student type',
      'LBL_TYPE': 'Type',
      'LBL_ATTENDANCE_DO_HOMEWORK': 'Do homework?',
      'LBL_ATTENDANCE_LOYALTY_POINT': 'Loyalty point',
      'LBL_ATTENDANCE_DAILY_SCORE': 'Daily score',
      'LBL_ATTENDANCE_CARE_COMMENT': 'Care\'s comments',
      'LBL_CONFIRM_NAVIGATION': 'Confirm navigation',
      'LBL_CONFIRM_NOTIFICATION': 'Confirm send',
      'LBL_CONFIRM_NOTIFICATION_CONTENT':
          'Are you sure you want to send notification?',
      'LBL_CONFIRM_NAVIGATION_CONTENT': 'Are you sure you want to leave?',
      'LBL_DIALOG_NO': 'NO',
      'LBL_DIALOG_YES': 'YES',

      // List String
      'Male': 'Male',
      'Month': 'Month',
      'Week': 'Week',
      'Female': 'Female',
      'Monday': 'Monday',
      'Tuesday': 'Tuesday',
      'Wednesday': 'Wednesday',
      'Thursday': 'Thursday',
      'Friday': 'Friday',
      'Saturday': 'Saturday',
      'Sunday': 'Sunday',
      'not_stated': 'Not started',
      'in_progress': 'In Process',
      'finished': 'Finished',
      'P': '✓ Present',
      'L': '◷ Late',
      'A': '✗ Absent',
      'E': '⛒ Excused',
      'none': 'None',
      'Unpaid': 'Unpaid',
      'Paid': 'Paid',
      'Cash': 'Cash',
      'Card': 'Card',
      'Bank Transfer': 'Bank Transfer',
      'Other': 'Other',
      'invalid_username': 'Invalid phone number',
      'invalid_code': 'Invalid code',

      // Notification
      'LBL_CHANGE_PASS_SUCCESS': 'Your password has been changed!',
      'LBL_TAP_TO_EXIT': 'Press back again to exit',

      'LBL_CHANGE_PASS_FAIL': 'Sometime went wrong :(',
      'LBL_GALLERY': 'Photo gallery',
      //'LBL_CLASS_PROGRESS_TEXT': 'session completed',
      'LBL_CLASS_PROGRESS_TEXT': 'session',
      'LBL_TEACHER_REVIEW': 'Teacher review',
      'LBL_TEACHER_ATTENDANCE': 'Attendance',
      'LBL_NAME_ATTENDANCE': 'Student name',

      // Reuquest update
      'LBL_IGNORE': 'Ignore',
      'LBL_LATER': 'Later',
      'LBL_UPDATE_NOW': 'Update',
      'LBL_PROMT':
          'A new version is available! Would you like to update it now?',
      'LBL_TITLE_UPDATE': 'Update App?',

      // Settings
      'LBL_SETTINGS': 'Settings',
      'LBL_COMMON': 'Common',
      'LBL_LANGUAGES': 'Language',
      'LBL_INFO': 'Information',
      'LBL_ACCOUNT': 'Account',
      'LBL_EMAIL': 'Email',
      'LBL_SIGN_OUT': 'Sign out',
      'LBL_SECURITY': 'Security',
      'LBL_FINGER': 'Use fingerprint',
      'LBL_MISC': 'Misc',
      'LBL_TERMS': 'Terms of Service',
      'LBL_LICENSES': 'Open source licenses',
      'LBL_CURRENT_LANG': 'English',
      'LBL_CAMERA': 'Camera',
      'LBL_RATE': 'Rate course:',
      'LBL_CALL_HOTLINE': 'Call now',

      //Pull to refresh
      'LBL_PULL_TO_REFRESH': 'Pull to refresh',
      'LBL_RELEASE_TO_REFRESH': 'Release to refresh',
      'LBL_REFRESHING': 'Refreshing',
      'LBL_COMPLETED_REFRESH': 'Completed',
      'LBL_CENTER_NAME': 'Center name',
      'Finished': 'Finished',
      'In Progress': 'In Progress',
      'LBL_NON_SUBJECT': 'Lesson name is empty!',
      'LBL_INFOR_LESSON': 'Schedule information',
      'LBL_NO_DATA_LESSON': 'No data available!',

      'LBL_RESEND_CODE': 'Resend',
      'LBL_TIME_LIMIT_CODE': 'The code will expire later',
      'LBL_ENTER_NEW_PASSWORD': 'Set Your Password',
      'LBL_ENTER_CODE_VERIFICATION': 'Your verification code is sent by SMS to',
      'LBL_PLEASE_WAIT_CODE': 'Please wait',
      'LBL_SEND_CODE_BACK': 'seconds to resend.',
      'LBL_NOT_RECEIVE_CODE': 'Did not receive the code?',
      'LBL_NEXT': 'Next',
      'LBL_OR_TRY': 'or try',
      'LBL_CONTACT_CENTER': 'contact center',
      'LBL_POLICY_PASSWORD': 'Password must be 6-16 characters long.',
      'LBL_CHANGE_PASS_DONE': 'Password changed successfully',
      'AM': 'am',
      'PM': 'pm',
      'LBL_SAVE_DONE': 'Saved successfully!',

      //Loyalty
      'LBL_PAYMENT_NAME': 'Payment name',
      'LBL_DESCRIPTION_LOYALTY': 'Description',
      'LBL_MENU_HOME_INTRO':
          'You click here to return the <strong> home screen </strong>.',
      'LBL_ACCUMULATION': 'Accumulation History',

      'LBL_MENU_HOME_INTRO':
          'You click here to return the <strong> home screen </strong>.',
      'LBL_MENU_FEEDBACK_INTRO':
          'If you want to know about <strong> tuition, timetable ,sick leave </strong> or <strong> questions </strong> click here.',
      'LBL_DOCUMENT_INTRO':
          'If you want to view <strong> documents, audio, video </strong> click here.',
      'LBL_MENU_PROFILE_INTRO':
          'If you want to update the <strong> personal information </strong> click here.',

      //Attendance
      'LBL_SELECT_SEND_NOTIFICATIONS': 'Send notifications',
      'LBL_EXCUSED': 'EXCUSED',
      'LBL_CONFIRM_ATTENDANCE': 'Confirm & send notifications',
      'LBL_SEND_NOTIFICATIONS': 'Notifications',
      'LBL_SENT': 'Sent',
      'LBL_SENDING': 'Sending',
      'LBL_PUSH_NOTIFICATIONS': 'Send Notifications',
      'LBL_CHECK_ALL': 'Check all',
      'LBL_LOGOUT_TITLE': 'Do you wish to sign out?',
      'LBL_LOGOUT_CONTENT': 'Signing out will clear data cached in device',
      'LBL_ABSENT': 'Absent',
      'LBL_JUSTIFIED': 'Justified',
      'LBL_UNJUSTIFIED': 'Unjustified',
      'LBL_MARK_ALL': 'Mark all',
      'LBL_UNCHECK': 'None',
      'LBL_PRESENT': 'Present',
      'LBL_LATE': 'Late',
      'LBL_A_JUSTIFIED': 'Justified',
      'LBL_A_UNJUSTIFIED': 'Unjustified',
      'LBL_TOTAL': 'Total',

      //Gallery
      'LBL_DOWNLOAD': 'Download',
      'LBL_CLASS': 'Class',

      'LBL_CLASSES': 'Classes',
      'LBL_SHARE': 'Share',
      'LBL_PHOTO': 'photo',
      'LBL_PHOTOS': 'photos',
      'LBL_ADDED': 'added',
      'LBL_DOWNLOAD_DONE': 'Download successfully',
      'LBL_DOWNLOAD_FAIL': 'Error! An error occurred',
      'LBL_ALBUM': 'album',
      'LBL_TO': 'to',
      'LBL_CREATE_ALBUM': 'Create Album',
      'LBL_ALBUM_NAME': 'Album name',
      'LBL_SEARCH': 'Search',
      'LBL_POSTING_1': '1 album is posting about this',
      'LBL_POSTING_N': 'albums are posting about this',

      //Home
      'LBL_NO_FEATURED_POST': 'No featured post',
      'LBL_TOOLKIT': 'Tools',
      'LBL_SYLLABUS': 'Syllabus',
      'LBL_EXAM': 'Exam',

      //Profile
      'LBL_CONFIRM': 'Confirm',
      'LBL_SEE_MORE': 'See more',
      'LBL_PERSONAL_SETTINGS': 'Personal Settings',
      'LBL_UPDATE_AVATAR': 'Update Avatar',
      'LBL_UPDATE_COVER': 'Update Cover',
      'LBL_UPDATE_INFORMATION': 'Update Information',

      // Class
      'LBL_IN_PROGRESS': 'In Progress',
      'LBL_FINISHED': 'Finished',
      'LBL_OVERVIEW': 'Overview',
      'LBL_SCHEDULE': 'Schedule',
      'LBL_PROGRESS': 'Progress',

      // Drawer
      'LBL_STUDENT_LIST': 'Student list',
    };
  }

  @override
  Map<String, Map<String, String>> get keys =>
      {'en_US': _buildLangEn(), 'vi_VN': _buildLangVn()};
}

void setLanguages(String? languageCode, String? countryCode) async {
  final prefs = await SharedPreferences.getInstance();

  if (languageCode == null && countryCode == null) {
    String? _langCode = prefs.getString('languageCode');
    String? _countryCode = prefs.getString('countryCode');
    if (!(_langCode?.isEmpty ?? true) && !(_countryCode?.isEmpty ?? true)) {
      Get.updateLocale(Locale(_langCode ?? 'en', _countryCode));
    }
  } else {
    Get.updateLocale(Locale(languageCode!, countryCode));
    prefs.setString('languageCode', languageCode);
    prefs.setString('countryCode', countryCode!);
  }
}
